main: link.ryhn.jpt.JustPlaceholderTab
name: JustPlaceholderTab
version: 1.0
api-version: 1.19
depend: [PlaceholderAPI]
permissions:
  jpt.command.reloadtablist:
    default: op
commands:
   reloadtablist:
      description: Reload the tablist format and apply it
      usage: /<command>
      permission: jpt.command.reloadtablist